### ISSUE TITLE
list_compartments for identity

### ISSUE THREAD

**Issue by vladcristi** [oracle/oci-python-sdk#125]
When I'm trying to use:
```
identity = oci.identity.IdentityClient(config)
identity.list_compartments(config["compartment"], access_level="ANY", compartment_id_in_subtree=True).data
```

I receive the following error: 

```Traceback (most recent call last):
  File "check_for_duplicates.py", line 177, in <module>
    list_compartments_response = identity.list_compartments(config["compartment"], access_level="ANY", compartment_id_in_subtree=True).data
  File "/usr/lib/python3.6/site-packages/oci/identity/identity_client.py", line 2723, in list_compartments
    "list_compartments got unknown kwargs: {!r}".format(extra_kwargs))
ValueError: list_compartments got unknown kwargs: ['access_level', 'compartment_id_in_subtree']
```

**Comment by arthall** [comment]
What version of the SDK are you using?  The kwargs access_level and compartment_id_in_subtree were added with version 2.0.6.  Based on the line numbers it looks like you have an older version of the SDK.

**Comment by vladcristi** [comment]
Yes! That was my problem, I was having an older version. Thank you @arthall
