### ISSUE TITLE
TypeError with announcement service

### ISSUE THREAD

**Issue by kranthor** [oracle/oci-python-sdk#161]
Just in the last 2 days started getting errors with a script that had been running fine for weeks. Seeing the same issue with OCI client when trying to list announcements now. I suspect something changed on API side, but seeking confirmation if anyone else is seeing the  issue. Updated to latest OCI and OCI-CLI versions, no change.

The error comes immediately with either

announce_client.list_announcements(compartment)

or 

response = oci.pagination.list_call_get_all_results(announce_client.list_announcements, compartment)

$ oci/scripts/oci-announce-report.py --tenancy=private
Traceback (most recent call last):
  File "oci/scripts/oci-announce-report.py", line 144, in <module>
    response = oci.pagination.list_call_get_all_results(announce_client.list_announcements, tenancy)
  File "oci/lib/python2.7/site-packages/oci/pagination/pagination_utils.py", line 203, in list_call_get_all_results
    for response in list_call_get_all_results_generator(list_func_ref, 'response', *list_func_args, **list_func_kwargs):
  File "oci/lib/python2.7/site-packages/oci/pagination/pagination_utils.py", line 271, in list_call_get_all_results_generator
    call_result = retry.DEFAULT_RETRY_STRATEGY.make_retrying_call(list_func_ref, *list_func_args, **list_func_kwargs)
  File "oci/lib/python2.7/site-packages/oci/retry/retry.py", line 271, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "oci/lib/python2.7/site-packages/oci/announcements_service/announcement_client.py", line 363, in list_announcements
    response_type="AnnouncementsCollection")
  File "oci/lib/python2.7/site-packages/oci/retry/retry.py", line 271, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "oci/lib/python2.7/site-packages/oci/base_client.py", line 225, in call_api
    response = self.request(request)
  File "oci/lib/python2.7/site-packages/oci/base_client.py", line 351, in request
    deserialized_data = self.deserialize_response_data(response.content, response_type)
  File "oci/lib/python2.7/site-packages/oci/base_client.py", line 545, in deserialize_response_data
    res = self.__deserialize(response_data, response_type)
  File "oci/lib/python2.7/site-packages/oci/base_client.py", line 588, in __deserialize
    return self.__deserialize_model(data, cls)
  File "oci/lib/python2.7/site-packages/oci/base_client.py", line 661, in __deserialize_model
    setattr(instance, attr, self.__deserialize(value, attr_type))
  File "oci/lib/python2.7/site-packages/oci/base_client.py", line 565, in __deserialize
    for sub_data in data]
  File "oci/lib/python2.7/site-packages/oci/base_client.py", line 588, in __deserialize
    return self.__deserialize_model(data, cls)
  File "oci/lib/python2.7/site-packages/oci/base_client.py", line 661, in __deserialize_model
    setattr(instance, attr, self.__deserialize(value, attr_type))
  File "oci/lib/python2.7/site-packages/oci/base_client.py", line 586, in __deserialize
    return self.__deserialize_datetime(data)
  File "oci/lib/python2.7/site-packages/oci/base_client.py", line 633, in __deserialize_datetime
    naivedatetime = datetime.strptime(string, "%Y-%m-%dT%H:%M:%S.%fZ")
TypeError: must be string, not int

similar issue seen from oci cli:

$ oci --config-file=my.cfg announce announcements list --compartment-id=ocid1.tenancy.oc1..abcdefghijklmnopqrstuvwxyz....
TypeError: must be string, not int

**Comment by adizohar** [comment]
Issue across the board, CLi ; SDK

Issue with the response from the service - https://announcements.us-ashburn-1.oraclecloud.com/20180904/announcements

header_params = <class 'dict'>: {'accept': 'application/json', 'content-type': 'application/json', 'opc-client-info': 'Oracle-PythonSDK/2.3.1', 'user-agent': 'Oracle-PythonSDK/2.3.1 (python 3.7.3; x86_64-Darwin)', 'opc-request-id': '0597BFCB37474003923F209F7B4DBE2C'}
query_params = <class 'dict'>: {'compartmentId': 'ocid1.tenancy.oc1..xxxxx', 'lifecycleState': 'ACTIVE', 'sortBy': 'timeCreated'}
response_type = 'AnnouncementsCollection'
URL = 'https://announcements.us-ashburn-1.oraclecloud.com/20180904/announcements'

Fail on base_client.py - line 361 - deserialized_data = self.deserialize_response_data(response.content, response_type)

I checked the returned value from the API
for AnnouncementSummary - time_created + time_updated are datetime
But the API returned int.

Example of returned item:
{
    "type":"AnnouncementSummary",
    "id":"ocid1.announcement.oc1..aaaaaaaaeqbovcb5id6wghizurwvjegoheum5c5ry4hagedfiaviy7b56ycq",
    "referenceTicketNumber":"CN-5459",
    "summary":"Reminder",
    "timeOneTitle":"Start Time",
    "timeOneType":"START_TIME",
    "timeOneValue":null,
    "timeTwoTitle":null,
    "timeTwoType":null,
    "timeTwoValue":null,
    "services":["Oracle Cloud Infrastructure Exadata"],
    "affectedRegions":["us-ashburn-1"],
    "announcementType":"SCHEDULED_MAINTENANCE",
    "lifecycleState":"ACTIVE",
    "isBanner":false,
    "timeCreated":1562214560182,
    "timeUpdated":1562214560182
}

**Comment by kranthor** [comment]
Thanks for the confirmation, will file bug with OCI.

**Comment by jodoglevy** [comment]
Announcements service is working on a fix

**Comment by jodoglevy** [comment]
The announcements team today said they have fixed this issue. Closing this.
