### ISSUE TITLE
certificate verify failed while posting to API

### ISSUE THREAD

**Issue by s92025592025** [oracle/oci-python-sdk#181]
OpenSSL Version
```
python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1d  10 Sep 2019
```

I tried getting user info and it worked fine
```
config = oci.config.from_file("~/.oci/config", "DEFAULT")

identity = oci.identity.IdentityClient(config)
user = identity.get_user(config["user"]).data
print(user)
```

But when I try to send message into a stream with the following code
```
streamClient = oci.streaming.StreamClient(config, service_endpoint="https://api.cell-1.us-phoenix-1.streaming.oci.oraclecloud.com")
encodedKey = b64encode("messageKey".encode()).decode()
encodedMsg1 = b64encode("someMessgaeValue1".encode()).decode()
encodedMsg2 = b64encode("someMessgaeValue2".encode()).decode()
putMessageDetails = oci.streaming.models.PutMessagesDetails(messages=[
		oci.streaming.models.PutMessagesDetailsEntry(key=encodedKey, value=encodedMsg1),
		oci.streaming.models.PutMessagesDetailsEntry(key=encodedKey, value=encodedMsg2)
	])

response = streamClient.put_messages(<stream ocid>,
									 putMessageDetails)
```

I would get the following error
```
Traceback (most recent call last):
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/urllib3/contrib/pyopenssl.py", line 457, in wrap_socket
    cnx.do_handshake()
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/urllib3/connectionpool.py", line 598, in urlopen
    self._prepare_proxy(conn)
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/urllib3/connectionpool.py", line 809, in _prepare_proxy
    conn.connect()
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/urllib3/connection.py", line 348, in connect
    ssl_context=context)
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/urllib3/util/ssl_.py", line 348, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/urllib3/contrib/pyopenssl.py", line 463, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/requests/adapters.py", line 454, in send
    enforce_content_length=True
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/urllib3/connectionpool.py", line 642, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/urllib3/util/retry.py", line 402, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
oci._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cell-1.us-phoenix-1.streaming.oci.oraclecloud.com', port=443): Max retries exceeded with url: /20180418/streams/ocid1.stream.oc1.phx.aaaaaaaamuzdoiyrhe3swxabtcopdboot2mk3kwtbz7cv5aneyue27gwu3sq/messages (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/base_client.py", line 343, in request
    timeout=self.timeout)
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/requests/sessions.py", line 537, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/requests/sessions.py", line 650, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/_vendor/requests/adapters.py", line 519, in send
    raise SSLError(e, request=request)
oci._vendor.requests.exceptions.SSLError: HTTPSConnectionPool(host='api.cell-1.us-phoenix-1.streaming.oci.oraclecloud.com', port=443): Max retries exceeded with url: /20180418/streams/ocid1.stream.oc1.phx.aaaaaaaamuzdoiyrhe3swxabtcopdboot2mk3kwtbz7cv5aneyue27gwu3sq/messages (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sendDataToStream.py", line 21, in <module>
    putMessageDetails)
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/streaming/stream_client.py", line 666, in put_messages
    enforce_content_headers=False)
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/base_client.py", line 235, in call_api
    response = self.request(request)
  File "/Users/jiuwang/Documents/jenkins-slack-intg/ENV/lib/python3.7/site-packages/oci/base_client.py", line 352, in request
    raise exceptions.RequestException(e)
oci.exceptions.RequestException: HTTPSConnectionPool(host='api.cell-1.us-phoenix-1.streaming.oci.oraclecloud.com', port=443): Max retries exceeded with url: /20180418/streams/ocid1.stream.oc1.phx.aaaaaaaamuzdoiyrhe3swxabtcopdboot2mk3kwtbz7cv5aneyue27gwu3sq/messages (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

All the code above is running on MacOS Mohave 10.14.5 with Python 3.7.4 and the following packages
```
$ pip freeze
certifi==2019.9.11
cffi==1.13.1
chardet==3.0.4
configparser==4.0.2
cryptography==2.8
idna==2.6
oci==2.6.2
pycparser==2.19
pyOpenSSL==19.0.0
python-dateutil==2.8.0
pytz==2019.3
six==1.12.0
urllib3==1.22
```

**Comment by jodoglevy** [comment]
Update: We've reached out to the streaming service team on this

**Comment by ness2u** [comment]
Certificate verification happens on the client; you'll need to update your local certificate store to include the publically available cert/ca for oraclecloud.com

**Comment by jodoglevy** [comment]
@s92025592025  since we haven't heard from you, and the solution has been provided above, I'll be closing this. Feel free to reopen if you are still facing issues.
