### ISSUE TITLE
oci.apigateway.GatewayClient.list_gateways Throw Internal Server Error

### ISSUE THREAD

**Issue by adizohar** [oracle/oci-python-sdk#218]
It works on OCI CLI but not with Python SDK:

import oci

compartment="ocid1.compartment.oc1..aaaaaaaarmzwh267w5njhaora2sv54yhbinsrlvuatnghyvprfppu7f5cjza"
config = oci.config.from_file("~/.oci/config","orasenatdpltdevopsnetw03")

apigw = oci.apigateway.GatewayClient(config)
apigs = apigw.list_gateways(compartment_id=compartment,sort_by="displayName",lifecycle_state='ACTIVE').data

for ap in apigs:
    print ("\n" + ap.display_name + " - " + ap.id )

---------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "X:/My Work Oracle/OCI/showoci/apigateway.py", line 7, in <module>
    apigs = apigw.list_gateways(compartment_id=compartment,sort_by="displayName",lifecycle_state='ACTIVE')
  File "C:\Users\Adi Zohar\AppData\Local\Programs\Python\Python37\lib\site-packages\oci\apigateway\gateway_client.py", line 538, in list_gateways
    response_type="GatewayCollection")
  File "C:\Users\Adi Zohar\AppData\Local\Programs\Python\Python37\lib\site-packages\oci\base_client.py", line 239, in call_api
    response = self.request(request)
  File "C:\Users\Adi Zohar\AppData\Local\Programs\Python\Python37\lib\site-packages\oci\base_client.py", line 362, in request
    self.raise_service_error(request, response)
  File "C:\Users\Adi Zohar\AppData\Local\Programs\Python\Python37\lib\site-packages\oci\base_client.py", line 532, in raise_service_error
    original_request=request)
oci.exceptions.ServiceError: {'opc-request-id': '13B8E0E9A9C14E8EBB1DBF779A2D5075/DB099E8383AEBFD939FA160D3AB2C195/D500E6F95526A638CE673766DCEA4801', 'code': 'InternalError', 'message': 'Internal Server Error', 'status': 500}

---------------------------------------------------------------------------------------------------------------

Using OCI CLI works

oci api-gateway gateway list --compartment-id ocid1.compartment.oc1..aaaaaaaarmzwh267w5njhaora2sv54yhbinsrlvuatnghyvprfppu7f5cjza --profile orasenatdpltdevopsnetw03
{
  "data": {
    "items": [
      {
        "compartment-id": "ocid1.compartment.oc1..aaaaaaaarmzwh267w5njhaora2sv54yhbinsrlvuatnghyvprfppu7f5cjza",
        "defined-tags": {
          "ORACLE": {
            "DEF": "ocid1.saml2idp.oc1..aaaaaaaar7p53ckhbu2hfplk2fm3ldn4nqliviiod53dyryqdc542h2js42q/adi.zohar@oracle.com at 2020-02-05T15:36:04.350Z"
          }
        },
        "display-name": "Adi_Test_GW",
        "endpoint-type": "PUBLIC",
        "freeform-tags": {},
        "hostname": "fmg7j4gvrjtqykt7mwxwwtoawu.apigateway.us-ashburn-1.oci.customer-oci.com",
        "id": "ocid1.apigateway.oc1.iad.amaaaaaa45wjkcqa7jcxslo7qdyeahbf5x3npc3nzguhyekbwckmqqkndpba",
        "lifecycle-details": null,
        "lifecycle-state": "ACTIVE",
        "subnet-id": "ocid1.subnet.oc1.iad.aaaaaaaaqhssio5nnxax6trorye2bf6hayee5bpj3tzk2m5aq234bdqrob2q",
        "time-created": "2020-02-05T15:36:05.739000+00:00",
        "time-updated": "2020-02-05T15:37:11.070000+00:00"
      }
    ]
  },

**Comment by adizohar** [comment]
Issue with sort_by, once removed, it works
