### ISSUE TITLE
timeout osms attach 

### ISSUE THREAD

**Issue by chris93111** [oracle/oci-python-sdk#274]
Hi 

I try to attach instance to group osms in oci but i have always timeout

i am directly plug in internet (no proxy)

oci os-management managed-instance-group attach --managed-instance-group-id xxxxxx--managed-instance-id xxxxx -d

Traceback (most recent call last):
  File "/Users/chris/bin/oci", line 8, in <module>
    sys.exit(cli())
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/json_skeleton_utils.py", line 83, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/cli_util.py", line 749, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/services/os_management/src/oci_cli_os_management/generated/osmanagement_cli.py", line 158, in attach_managed_instance_to_managed_instance_group
    **kwargs
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci/os_management/os_management_client.py", line 333, in attach_managed_instance_to_managed_instance_group
    header_params=header_params)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci/retry/retry.py", line 272, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci/base_client.py", line 265, in call_api
    response = self.request(request)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci/base_client.py", line 371, in request
    raise exceptions.RequestException(e)
oci.exceptions.RequestException: HTTPSConnectionPool(host='osms.eu-frankfurt-1.oci.oraclecloud.com', port=443): Read timed out. (read timeout=60.0)

}[chris@MBP-de-FERREIRA:~ ] $ curl https://osms.eu-frankfurt-1.oci.oraclecloud.com/
{
  "code" : "NotAuthorizedOrNotFound",
  "message" : "Authorization failed or requested resource not found."
}[chris@MBP-de-FERREIRA:~ ] $ 

i tryed to set the timeout to 120 , result is same

**Comment by jodoglevy** [comment]
Hi @chris93111 - this looks like an OCI CLI issue. You've opened this issue against the OCI Python SDK. Can you please open this issue against the OCI CLI by filing the issue [here](https://github.com/oracle/oci-cli)?

**Comment by chris93111** [comment]
@jodoglevy ok is open 

thanks

**Comment by jodoglevy** [comment]
Closing this ticket as https://github.com/oracle/oci-cli/issues/313 has been filed for the same
