### ISSUE TITLE
File "/root/oci-python/oci-python-sdk/examples/showoci/showoci_output.py", line 2351, in generate_csv

### ISSUE THREAD

**Issue by goldiesharma** [oracle/oci-python-sdk#287]
Hi,

I am getting below error when generating csv report, could you please check what could be the issue here?

##########################################################################################
#                                     Summary Total                                      #
##########################################################################################
Compute - Block Storage (GB)..........................................5137
Compute - VM.Standard2.1  - Oracle Linux.................................1
Compute - VM.Standard2.2  - Windows-Server-2012..........................2
Compute - VM.Standard2.4  - Oracle Linux.................................3
Compute - VM.Standard2.4  - Windows-Server-2012..........................2
Compute - VM.Standard2.4  - Windows-Server-2016..........................2
File Storage (GB).......................................................65
Load Balancer 400Mbps....................................................3
Object Storage - Buckets (GB)............................................0
Total OCPUs - Compute...................................................33

##########################################################################################
#                                  Processing CSV Files                                  #
##########################################################################################
Traceback (most recent call last):
  File "/root/oci-python/oci-python-sdk/examples/showoci/showoci_output.py", line 2403, in __export_to_csv_file
    with open(file_name, mode='w', newline='') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/nfs/Documents/Project_Level_Documents/OCI/OCI_INVENTORY_DATA//ocivpappusms131/ashburn-1/_identity_compartments.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/oci-python/oci-python-sdk/examples/showoci/showoci_output.py", line 2351, in generate_csv
    self.__export_to_csv_file("identity_compartments", self.csv_identity_compartments)
  File "/root/oci-python/oci-python-sdk/examples/showoci/showoci_output.py", line 2415, in __export_to_csv_file
    raise Exception("Error in __export_to_csv_file: " + str(e.args))
Exception: Error in __export_to_csv_file: (2, 'No such file or directory')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/oci-python/oci-python-sdk/examples/showoci/showoci.py", line 451, in <module>
    execute_extract()
  File "/root/oci-python/oci-python-sdk/examples/showoci/showoci.py", line 206, in execute_extract
    csv.generate_csv(extracted_data, cmd.csv)
  File "/root/oci-python/oci-python-sdk/examples/showoci/showoci_output.py", line 2371, in generate_csv
    raise Exception("Error in generate_csv: " + str(e.args))
Exception: Error in generate_csv: ("Error in __export_to_csv_file: (2, 'No such file or directory')",)

**Comment by goldiesharma** [comment]
it was small typo on script, got it fixed.
