### ISSUE TITLE
VirtualNetworkClient function get_vnic not working under oci.pagination.list_call_get_all_results

### ISSUE THREAD

**Issue by aegiacometti** [oracle/oci-python-sdk#315]
Plain call to the function works fine:
`get_vnic_response = virtual_network.get_vnic(vnic_id)`

I'm using a lot this function to handle the retries **oci.pagination.list_call_get_all_results**.

When I wrap it there with:
`get_vnic_response = oci.pagination.list_call_get_all_results(
        virtual_network.get_vnic,
        vnic_id
    ).data`

I get this traceback:
```
Traceback (most recent call last):
  File "/home/adrian/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/helpers/pydev/pydevd.py", line 2073, in <module>
    main()
  File "/home/adrian/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/helpers/pydev/pydevd.py", line 2067, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/adrian/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/helpers/pydev/pydevd.py", line 1418, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/adrian/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/helpers/pydev/pydevd.py", line 1425, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/adrian/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/adrian/projects/pychatops/scripts/oci/test.py", line 233, in <module>
    retry_strategy=oci.retry.DEFAULT_RETRY_STRATEGY
  File "/usr/local/lib/python3.6/dist-packages/oci/pagination/pagination_utils.py", line 218, in list_call_get_all_results
    else aggregated_results.extend(call_result.data.items)
AttributeError: 'Vnic' object has no attribute 'items
```

While debugging I can see that the GET response is fine.
But in this line, the conditional might get it in the wrong way.
File **pagination_utils.py** line 217-218.

```
aggregated_results.extend(call_result.data) if isinstance(call_result.data, list) \
   else aggregated_results.extend(call_result.data.items)
```

**Comment by adizohar** [comment]
Hi aegiacometti
The list_call_get_all_results can only be used for list operation not get, the name of the function also "list call get..."
Please follow the documentation
https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/pagination.html
Thank you

**Comment by aegiacometti** [comment]
Thanks Adi. Good point.The retry options are for retrying http gets or I get it wrong then?Adrián.-El 29 dic. 2020 18:56, Adi Zohar <notifications@github.com> escribió:
Hi aegiacometti
The list_call_get_all_results can only be used for list operation not get, the name of the function also "list call get..."
Please follow the documentation
https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/pagination.html
Thank you

**Comment by adizohar** [comment]
The retry option can be used for each call, 
But the pagination can be used only for list.

You can check the showoci in the examples for retry.

**Comment by aegiacometti** [comment]
yes, Perfect!
Thanks Adi for your help.
Have a great 2021
