### ISSUE TITLE
Run in issue with Check Access to Cost and Usage Object Storage

### ISSUE THREAD

**Issue by cc13com** [oracle/oci-python-sdk#350]
Hello,

I will follow your setup to have the cost and usage report in an APEX application. Since I already have a compute VM and a database running and want to use them for this purpose I skipped the first steps in your manual (creating VM and DB).

But I run in an issue with point 9 "Check connectivity...". It shows me the following:
```
Connecting to Identity Service...
   Okay.

   Check Tenancy Details Access...
   Okay.

   Get List of Regions...
   Okay.

   Check running in home region...
   Home    Region = eu-frankfurt-1
   Current Region = eu-frankfurt-1
   Okay.

   Check Compartment List Access...
   Okay...

   Check Access to Cost and Usage Object Storage...
Error oci.exceptions.ServiceError
{'opc-request-id': 'fra-1:***', 'code': 'BucketNotFound', 'message': "Either the bucket named 'ocid1.tenancy.oc1..***' does not exist in the namespace 'bling' or you are not authorized to access it", 'status': 404}
```

Dynamic group and policy is created. Any idea where I can check what's wrong?

**Comment by adizohar** [comment]
Hi 
In order to access the usage and cost file, you must run on your home region
to check if you have access you can use the OCI CLI below, just add your tenant_id as the bucket name

oci os object list --namespace-name bling --auth instance_principal --bucket-name ocid1.tenancy.oc1..aa..

**Comment by cc13com** [comment]
Hi,

If I run this code I get the following (I used my tenant_id:

```
[opc@instance-cc13 ~]$ oci os object list --namespace-name bling --auth instance_principal --bucket-name ocid1.tenancy.oc1..aaaa.....
Traceback (most recent call last):
  File "/usr/local/bin/oci", line 7, in <module>
    from oci_cli.cli import cli
  File "/usr/local/lib/python3.6/site-packages/oci_cli/__init__.py", line 39, in <module>
    from .cli_root import cli  # noqa: F401,E402
  File "/usr/local/lib/python3.6/site-packages/oci_cli/cli_root.py", line 22, in <module>
    from . import cli_util  # noqa: E402
  File "/usr/local/lib/python3.6/site-packages/oci_cli/cli_util.py", line 40, in <module>
    from .cli_clients import CLIENT_MAP, MODULE_TO_TYPE_MAPPINGS
  File "/usr/local/lib/python3.6/site-packages/oci_cli/cli_clients.py", line 34, in <module>
    __import__(ALL_SERVICES_DIR + '.' + modname1 + '.src.' + oci_cli_module_name + ".generated." + generated_module)
  File "/usr/local/lib/python3.6/site-packages/services/ai_language/src/oci_cli_ai_service_language/generated/client_mappings.py", line 8, in <module>
    from oci.ai_language import AIServiceLanguageClient
ModuleNotFoundError: No module named 'oci.ai_language'
```

What do you mean with your last sentence? If I login via browser to the console and open Cost Management/Cost and Usage Reports I see all usage/cost csv files listet.

**Comment by adizohar** [comment]
Hi
First need to fix the OCI CLI to check your permission, please update OCI and OCI CLI packages

pip3 install —upgrade oci oci-cli

once install run the oci command again

can you please share the dynamic group and the policy ?

thank you

**Comment by cc13com** [comment]
Hi,

I had to run `pip3 install -U oci oci-cli` and as root to get it updated without error messages.

Now I run the oci command again:

```
[opc@instance-cc13 ~]$ oci os object list --namespace-name bling --auth instance_principal --bucket-name ocid1.instance.oc1.eu-frankfurt-1.ant...
ServiceError:
{
    "code": "BucketNotFound",
    "message": "Either the bucket named 'ocid1.instance.oc1.eu-frankfurt-1.ant....' does not exist in the namespace 'bling' or you are not authorized to access it",
    "opc-request-id": "fra-1:TgdT-....",
    "status": 404
}
```

The instance ID I use in the oci command is the same like in the dynamic group. And this ID is showing in the compute instance OCID field:

Dynamic Group:

![Bildschirmfoto 2021-05-23 um 18 22 43](https://user-images.githubusercontent.com/35263232/119268600-04179200-bbf4-11eb-9217-a533289dc976.jpg)


Policy:

<img width="1365" alt="Bildschirmfoto 2021-05-23 um 18 14 55" src="https://user-images.githubusercontent.com/35263232/119268375-f57cab00-bbf2-11eb-97dc-a8219dcaec1c.png">

**Comment by cc13com** [comment]
OK, I run the check again:

```
[opc@instance-cc13 setup]$ ./check_connectivity.py

   Connecting to Identity Service...
   Okay.

   Check Tenancy Details Access...
   Okay.

   Get List of Regions...
   Okay.

   Check running in home region...
   Home    Region = eu-frankfurt-1
   Current Region = eu-frankfurt-1
   Okay.

   Check Compartment List Access...
   Okay...

   Check Access to Cost and Usage Object Storage...
   Okay.

   Check Access to OCI Public Rates URL (Required Internet Access)...
   Okay.

   Check Completed Successfully.
   Tenant Name : cc13
   Tenant Id   : ocid1.tenancy.oc1..aaaaa......
```

Looks better, but running the setup runs in an error:

```
[opc@instance-cc13 setup]$ ./setup_usage2adw.sh
##################################################
# Start process at So 23. Mai 18:28:17 CEST 2021
##################################################

1. Read Variables from config.user file.

2. Extract database wallet.
Archive:  /home/opc/wallet.zip
  inflating: /home/opc/ADWCUSG/README
  inflating: /home/opc/ADWCUSG/cwallet.sso
  inflating: /home/opc/ADWCUSG/tnsnames.ora
  inflating: /home/opc/ADWCUSG/truststore.jks
  inflating: /home/opc/ADWCUSG/ojdbc.properties
  inflating: /home/opc/ADWCUSG/sqlnet.ora
  inflating: /home/opc/ADWCUSG/ewallet.p12
  inflating: /home/opc/ADWCUSG/keystore.jks
   Database Wallet extracted successfully

3. Fixing sqlnet.ora directory parameter
   Done.

4. Checking OCI Connectivity using instance principles...
   Executed: python3 check_connectivity.sh

   Connecting to Identity Service...
   Okay.

   Check Tenancy Details Access...
   Okay.

   Get List of Regions...
   Okay.

   Check running in home region...
   Home    Region = eu-frankfurt-1
   Current Region = eu-frankfurt-1
   Okay.

   Check Compartment List Access...
   Okay...

   Check Access to Cost and Usage Object Storage...
   Okay.

   Check Access to OCI Public Rates URL (Required Internet Access)...
   Okay.

   Check Completed Successfully.
   Tenant Name : cc13
   Tenant Id   : ocid1.tenancy.oc1..aaaaa......

   Okay.

5. Creating USAGE user on ADWC instance and enable APEX Workspace
   commands executed:
   sqlplus ADMIN/xxxxx@DB21c_low
   create user usage identified by xxxxx;
   grant create dimension, connect, resource, dwrole, unlimited tablespace to usage;
   exec apex_instance_admin.add_workspace(p_workspace => 'USAGE', p_primary_schema => 'USAGE');
./setup_usage2adw.sh: Zeile 119: sqlplus: Kommando nicht gefunden.
grep: /home/opc/usage_reports_to_adw/setup/log/db_creation_user.log: Datei oder Verzeichnis nicht gefunden
   Okay.

6. Create USAGE Tables and Import APEX application
   sqlplus USAGE/xxxx@DB21c_low @/home/opc/usage_reports_to_adw/setup/create_tables.sql
   sqlplus USAGE/xxxx@DB21c_low @/home/opc/usage_reports_to_adw/setup/enable_apex.sql
./setup_usage2adw.sh: Zeile 142: sqlplus: Kommando nicht gefunden.
grep: /home/opc/usage_reports_to_adw/setup/log/create_table_enable_apex.log: Datei oder Verzeichnis nicht gefunden
   Okay.

7. Setup Crontab to run every 3 hours and gather stats every week
Executed: crontab /home/opc/usage_reports_to_adw/setup/setup.crontab.txt

###############################################################
# Running Initial usage2adw.py extract
###############################################################
   Command line:
   python3 usage2adw.py -ip -du USAGE -dp xxxx -dn DB21c_low -d 2021-04 -ts Oracle-Tags.CreatedBy


##########################################################################################
#                               Running Usage Load to ADW                                #
##########################################################################################
Starts at 2021-05-23 18:28:28
Command Line : -ip -du USAGE -dp xxxx -dn DB21c_low -d 2021-04 -ts Oracle-Tags.CreatedBy

Connecting to Identity Service...
   Tenant Name : cc13
   Tenant Id   : ocid1.tenancy.oc1..aaaaaa......
   App Version : 21.05.18
   Home Region : eu-frankfurt-1

Loading Compartments...
    Total 3 compartments loaded.

Connecting to database DB21c_low

Error manipulating database - DPI-1080: connection was closed by ORA-28547


############################################################################################
# If process complete successfuly, please continue and login to APEX
############################################################################################
```

In point 5 and 6 it means that cannot find command sqlplus.

**Comment by adizohar** [comment]
ORA-28547: connection to server failed, probable Oracle Net admin

sqlplus does not found, you need to install manually oracle instant client and add to the path 

Check the manual installation, point 7 - https://github.com/oracle/oci-python-sdk/blob/master/examples/usage_reports_to_adw/step_by_step_manual_installation.md

And run the setup again, it needs to create the tables + APEX app.

**Comment by cc13com** [comment]
Hi, 

weird, the manual I use has a different point 7 ([https://github.com/oracle/oci-python-sdk/blob/master/examples/usage_reports_to_adw/step_by_step_installation.md](url)

Will do with your manual I come back later today.

**Comment by cc13com** [comment]
Hi,

looks good now. After deleting App 100 in my other workspace and running again the setup-script I can login to the workspace and in the usage app.

Thanks for your help. I will now investigate the app.

Best,
Carsten

**Comment by adizohar** [comment]
Hi Carsten

Thank you for confirming
I pushed new version of the APEX app with more functionality , coming tomorrow
You can download it earlier from my git - https://github.com/adizohar/usage_reports_to_adw/tree/main/apex_demo_app

I would suggest you to delete the app 100 and import the new one or import as new app number

Once all completed, please close the ticket

Thank you

**Comment by cc13com** [comment]
Hi Adi,

I thought I closed the ticket yesterday with my last comment.

**Comment by dbafurushima** [comment]
Not.
Thank's for your time.
