### ISSUE TITLE
Folders with parallel_upload_to_object_storage.py

### ISSUE THREAD

**Issue by ralsouza** [oracle/oci-python-sdk#369]
Hi, 
I'm working with [parallel_upload_to_object_storage.py](https://github.com/oracle/oci-python-sdk/blob/master/examples/parallel_upload_to_object_storage.py), but I can't store my files in the internal folders into the bucket.

When I run this command 
`python3 parallel_upload_to_object_storage.py algorithms_dev_dscience  /home/datascience/data/20210715/csv`

My files are stored into root folder, but I want to store in subjacent folders. Like this:
`python3 parallel_upload_to_object_storage.py algorithms_dev_dscience/my_files  /home/datascience/data/20210715/csv`

At this moment I got this error:
`Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "parallel_upload_to_object_storage.py", line 39, in upload_to_object_storage
    in_file)
  File "/opt/conda/lib/python3.6/site-packages/oci/object_storage/object_storage_client.py", line 4233, in put_object
    enforce_content_headers=False)
  File "/opt/conda/lib/python3.6/site-packages/oci/base_client.py", line 426, in call_api
    response = self.request(request)
  File "/opt/conda/lib/python3.6/site-packages/oci/base_client.py", line 541, in request
    self.raise_service_error(request, response)
  File "/opt/conda/lib/python3.6/site-packages/oci/base_client.py", line 711, in raise_service_error
    original_request=request)
oci.exceptions.ServiceError: {'opc-request-id': 'gru-1:6Y8LyaFqdOdBGVgZvmcuxgWXODoJ2zPA7YYiJiqhWvf1VhIawn6XzY52FThf8sXy', 'code': 'NotFound', 'message': 'Not Found', 'status': 404}`

But, the folder exists.

Another strange thing, when I put the "o" folder after the bucket name, the command runs successfully and stores my files with this "o" folder. Like this:
![image](https://user-images.githubusercontent.com/11009855/125997001-cf7029ad-5f01-4c88-8404-cbc9fac57633.png)

**Comment by jodoglevy** [comment]
@ralsouza  thanks for reporting this issue - we'll forward this along to the Object Storage service team to take a look

**Comment by tsammut** [comment]
Hi @ralsouza.

Newer versions of the OCI CLI are quite fast. 

https://github.com/oracle/oci-cli/releases

The CLI also supports what you are trying to do. 

https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.26.4/oci_cli_docs/cmdref/os/object/bulk-upload.html#cmdoption-object-prefix

For example:

```
# My local files in a folder called folder

$ find folder
folder
folder/a
folder/b

# Upload in bulk, adding a parent directory

$ oci os object bulk-upload --bucket-name folder-test-bucket --src-dir folder --object-prefix new-parent-folder/folder/
Uploaded new-parent-folder/folder/b  [####################################]  100%
Uploaded new-parent-folder/folder/a  [####################################]  100%

{
  "skipped-objects": [],
  "upload-failures": {},
  "uploaded-objects": {
    "new-parent-folder/folder/a": {
      "etag": "8da4d865-4bb4-45ee-be86-497b56cc5996",
      "last-modified": "Thu, 02 Sep 2021 19:01:29 GMT",
      "opc-content-md5": "1B2M2Y8AsgTpgAmY7PhCfg=="
    },
    "new-parent-folder/folder/b": {
      "etag": "b6291baa-d1c5-4345-9750-c4066ffb346d",
      "last-modified": "Thu, 02 Sep 2021 19:01:29 GMT",
      "opc-content-md5": "1B2M2Y8AsgTpgAmY7PhCfg=="
    }
  }
}

# Verify results with an object listing

$ oci os object list --bucket-name folder-test-bucket | jq '.data | map(.name)'                                        
[
  "new-parent-folder/folder/a",
  "new-parent-folder/folder/b"
]
```

Might this work for you? Thanks!

**Comment by jodoglevy** [comment]
@ralsouza is your issue resolved based on the response provided by @tsammut ?

**Comment by KartikShrikantHegde** [comment]
Hi @ralsouza,

I will be closing this issue for now. Please feel free to reopen if required.

Thanks.
