### ISSUE TITLE
OCI signer and client throwing exceptions after 12 hours

### ISSUE THREAD

**Issue by ananyban** [oracle/oci-python-sdk#388]
Was trying to use Database client with resource principal signer:
self._client = DatabaseClient(config=config, signer=sign)
self._resource_search_client = ResourceSearchClient(config={},
                                                            signer=sign)

Got the following exception after ~12hours :

2021-09-22 05:32:09,469 : WARNING  : resourceinfo.py:82 : OCIResourceInfo: Error in getting aei info {'opc-request-id': 'EA#####713F5DBF6', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}
Traceback (most recent call last):
  File "/var/opt/oracle/adbd/apps/pylib/resourceinfo.py", line 77, in get_aei_info
    info = self._client.get_autonomous_exadata_infrastructure(autonomous_exadata_infrastructure_id=aei_ocid)
  File "/usr/local/lib/python3.6/site-packages/oci/database/database_client.py", line 7781, in get_autonomous_exadata_infrastructure
    response_type="AutonomousExadataInfrastructure")
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 270, in call_api
    return self.request(request)
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 394, in request
    self.raise_service_error(request, response)
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 564, in raise_service_error
    original_request=request)
oci.exceptions.ServiceError: {'opc-request-id': 'EA###6', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}

Saw that  in the oci python sdk source code (https://github.com/oracle/oci-python-sdk/blob/master/src/oci/auth/signers/resource_principals_federation_signer.py) the get_security_token method itself has a refresh mechanism if the security token is not valid. So this exception was unexpected. Does this mean the user have to worry about periodically (after every ~12hrs) refreshing the token ?

**Comment by jodoglevy** [comment]
@ananyban  thanks for reporting - we'll take a look.  Might be we have a bug in our resource principal token refresh logic
