### ISSUE TITLE
Allow control characters inside strings.

### ISSUE THREAD

**Issue by ezequielramos** [oracle/oci-python-sdk#404]
I'm having this error when trying to query an OCI NoQSL Tables.

```
Traceback (most recent call last):
  File "/mnt/5cb80605-c86e-4351-b941-96d1cb6eadab/Documents/Projects/camerite-remora-v2/regenerate_timeline.py", line 133, in <module>
    create_by_old_nosql()
  File "/mnt/5cb80605-c86e-4351-b941-96d1cb6eadab/Documents/Projects/camerite-remora-v2/regenerate_timeline.py", line 118, in create_by_old_nosql
    response: oci.nosql.models.QueryResultCollection = nosql_cli.query(
  File "/home/ezequiel/.pyenv/versions/camerite-remora-v2/lib/python3.9/site-packages/oci/nosql/nosql_client.py", line 1926, in query
    return retry_strategy.make_retrying_call(
  File "/home/ezequiel/.pyenv/versions/camerite-remora-v2/lib/python3.9/site-packages/oci/retry/retry.py", line 272, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "/home/ezequiel/.pyenv/versions/camerite-remora-v2/lib/python3.9/site-packages/oci/base_client.py", line 303, in call_api
    response = self.request(request)
  File "/home/ezequiel/.pyenv/versions/camerite-remora-v2/lib/python3.9/site-packages/oci/base_client.py", line 441, in request
    deserialized_data = self.deserialize_response_data(
  File "/home/ezequiel/.pyenv/versions/camerite-remora-v2/lib/python3.9/site-packages/oci/base_client.py", line 684, in deserialize_response_data
    res = self.__deserialize(response_data, response_type)
  File "/home/ezequiel/.pyenv/versions/camerite-remora-v2/lib/python3.9/site-packages/oci/base_client.py", line 734, in __deserialize
    return self.__deserialize_model(data, cls)
  File "/home/ezequiel/.pyenv/versions/camerite-remora-v2/lib/python3.9/site-packages/oci/base_client.py", line 817, in __deserialize_model
    value = data[property]
TypeError: string indices must be integers
```

This is happening because, for some reason, the OCI NoSQL Tables that I'm interacting with has "control characters" registered.

The solution is described on PR #403

**Comment by waruwaruwaru** [comment]
Hi @ezequielramos, which API are you calling that gave back the control characters? Are you able to share a snippet of the code where the failure occurred? Thank you.

**Comment by ezequielramos** [comment]
Sure @waruwaruwaru.

There's nothing too different on my code. The problem actually is on the data stored on the nosql.

```python
import oci
from oci import nosql
from oci.nosql.models import QueryDetails
from oci.retry import DEFAULT_RETRY_STRATEGY


next_page = None
has_next_page=True
compartment_id = '<compartment_id>'

nosql_cli = nosql.NosqlClient(
    {
        "user": 'user',
        "key_file": 'key_file',
        "fingerprint": 'fingerprint',
        "tenancy": 'tenancy',
        "region": 'region',
    },
    retry_strategy=DEFAULT_RETRY_STRATEGY,
)


while has_next_page:
    q = f"SELECT * FROM videos_timeline"
    details = QueryDetails(compartment_id=compartment_id, statement=q)
    response: oci.nosql.models.QueryResultCollection = nosql_cli.query(
        details, limit=1000, page=next_page
    )

    has_next_page = response.has_next_page
    next_page = response.next_page

    # my code goes here
```

**Comment by waruwaruwaru** [comment]
Hi @ezequielramos, the latest version of Python SDK should now have the ability to allow control characters. Here is an example of how to utilize this feature: https://github.com/oracle/oci-python-sdk/blob/master/examples/allow_control_characters_example.py

Here is a documentation on enabling this feature. https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/sdk_behaviors/allow_control_chars_response.html

I will close this issue, if you have any other problems or concern, please feel free to re-open this issue. Thank you.
