### ISSUE TITLE
Unable to create secret with length of name greater than 50 character

### ISSUE THREAD

**Issue by Kirandeep-Singh** [oracle/oci-python-sdk#424]
Hi Team

When I try to create a secret with name having length more than 50 characters, below exception is thrown.
However if we create the secret manually from OCI Console, its successfully created. Please support here.

`Traceback (most recent call last):
  File "C:\Data\GIT\opam_gsiv_migration\argus-min-jarvis\lib\argus_secret_management.py", line 195, in create_secret
    secret_create_response = vaults_management_client_composite.create_secret_and_wait_for_state(create_secret_details=secrets_details,
  File "C:\Data\GIT\opam_gsiv_migration\venv\lib\site-packages\oci\vault\vaults_client_composite_operations.py", line 44, in create_secret_and_wait_for_state
    operation_result = self.client.create_secret(create_secret_details, **operation_kwargs)
  File "C:\Data\GIT\opam_gsiv_migration\venv\lib\site-packages\oci\vault\vaults_client.py", line 495, in create_secret
    return self.base_client.call_api(
  File "C:\Data\GIT\opam_gsiv_migration\venv\lib\site-packages\oci\base_client.py", line 472, in call_api
    response = self.request(request, allow_control_chars)
  File "C:\Data\GIT\opam_gsiv_migration\venv\lib\site-packages\circuitbreaker.py", line 52, in wrapper
    return self.call(function, *args, **kwargs)
  File "C:\Data\GIT\opam_gsiv_migration\venv\lib\site-packages\circuitbreaker.py", line 67, in call
    result = func(*args, **kwargs)
  File "C:\Data\GIT\opam_gsiv_migration\venv\lib\site-packages\oci\base_client.py", line 601, in request
    self.raise_service_error(request, response, service_code, message)
  File "C:\Data\GIT\opam_gsiv_migration\venv\lib\site-packages\oci\base_client.py", line 758, in raise_service_error
    raise exceptions.ServiceError(
oci.exceptions.ServiceError: {'opc-request-id': 'A554FAC40F5B466D8E6D40A6B26E31C1/52F42F7F3FB49A3E707ED18AA8A24E36/A6275DE3AC1F9B99F908EDD1B9A6A1D6', 'code': 'InvalidParameter', 'message': 'secretContent.name size must be between 0 and 50', 'status': 400}`

**Comment by jodoglevy** [comment]
@Kirandeep-Singh  thanks for reporting, we'll ask the Key Vault team to take a look

**Comment by ramonidea** [comment]
Hi Kirandeep,

There are name fields both under [createSecretDetails](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/vault/models/oci.vault.models.CreateSecretDetails.html#oci.vault.models.CreateSecretDetails)  and [secretContentDetails](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/vault/models/oci.vault.models.SecretContentDetails.html#oci.vault.models.SecretContentDetails) , which caused this confusion. 

The name you provided in the console is the field called `secret_name` under `CreateSecretDetails`. The name under secretContentDetails is a name for the content, it is not the secret name, you can provide null or ignore for that field.

**Comment by Kirandeep-Singh** [comment]
Hi Ramon

Yeah I figured it out after posting query here.
Thanks for your response.
