### ISSUE TITLE
Specified object or bucket or namespace to import image from does not exist

### ISSUE THREAD

**Issue by franciscvass** [oracle/oci-python-sdk#438]
Hi,
while I'm trying to create a Custom image importing from a bucket I get the below error if I use instance or resource principal auth.

Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/usr/lib/python3.6/site-packages/oci/core/compute_client.py", line 1632, in create_image
    response_type="Image")
  File "/usr/lib/python3.6/site-packages/oci/base_client.py", line 463, in call_api
    return self.request(request, allow_control_chars)
  File "/usr/lib/python3.6/site-packages/oci/base_client.py", line 601, in request
    self.raise_service_error(request, response, service_code, message)
  File "/usr/lib/python3.6/site-packages/oci/base_client.py", line 763, in raise_service_error
    original_request=request)
oci.exceptions.ServiceError: {'opc-request-id': 'F7C432E7E06C468FA7F8016E6A36749D/997ABBB805CE790AA5D23B6288F0C2E2/D5DBE4CD5E115799B260CB46A8C4520E', 'code': 'InvalidParameter', 'message': 'Invalid objectName: Specified object or bucket or namespace to import image from does not exist', 'status': 400}

The same piece of code works If I'm using API key auth.

import oci
signer = oci.auth.signers.InstancePrincipalsSecurityTokenSigner()
core_client = oci.core.ComputeClient({}, signer=signer)
x = core_client.create_image(
        create_image_details = oci.core.models.CreateImageDetails(
            compartment_id          = "ocid1.compartment.o.....",
            launch_mode             = "NATIVE",
            image_source_details    = oci.core.models.ImageSourceViaObjectStorageUriDetails(
                #source_image_type   = "VMDK",
                source_uri          = "https://objectstorage.eu-frankfurt-1.o......."
               ,source_type = "objectStorageUri"
                )
            )
        )

Thanks.
Francisc

**Comment by franciscvass** [comment]
HI,
got an answer in:

https://github.com/oracle/oci-cli/issues/384

will try that.
Thanks.
