### ISSUE TITLE
Hitting TypeError when trying to fetch secrets in python 3.8

### ISSUE THREAD

**Issue by Kirandeep-Singh** [oracle/oci-python-sdk#450]
Hi Guys

I am facing an issue while using the sdk for python version 3.8.
Same piece of code runs fine without any issues for Python 3.6.

`import oci`
`region="test"`
`config_file=".oci_config_file"`
`config = oci.config.from_file(config_file, profile_name=region.upper())`
`vault_client = oci.vault.VaultsClient(config)`
`argus_compartment_id=config.get("argus_comp_id")`
`vault_id=config.get("vault_id")`
`secret_list = vault_client.list_secrets(name = "Dummy_secret", compartment_id=argus_compartment_id, vault_id=vault_id, lifecycle_state="ACTIVE")`

Error:

`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/lib/python3.8/site-packages/oci/vault/vaults_client.py", line 947, in list_secrets`
`    return self.base_client.call_api(`
`  File "/usr/lib/python3.8/site-packages/oci/base_client.py", line 472, in call_api`
`    response = self.request(request, allow_control_chars)`
`  File "/usr/lib/python3.8/site-packages/circuitbreaker.py", line 52, in wrapper`
`    return self.call(function, *args, **kwargs)`
`  File "/usr/lib/python3.8/site-packages/circuitbreaker.py", line 67, in call`
`    result = func(*args, **kwargs)`
`  File "/usr/lib/python3.8/site-packages/oci/base_client.py", line 570, in request`
`    response = self.session.request(`
`  File "/usr/lib/python3.8/site-packages/oci/_vendor/requests/sessions.py", line 547, in request`
`    resp = self.send(prep, **send_kwargs)`
`  File "/usr/lib/python3.8/site-packages/oci/_vendor/requests/sessions.py", line 660, in send`
`    r = adapter.send(request, **kwargs)`
`  File "/usr/lib/python3.8/site-packages/oci/_vendor/requests/adapters.py", line 446, in send`
`    resp = conn.urlopen(`
`  File "/usr/lib/python3.8/site-packages/oci/_vendor/urllib3/connectionpool.py", line 693, in urlopen`
`    conn = self._get_conn(timeout=pool_timeout)`
`  File "/usr/lib/python3.8/site-packages/oci/_vendor/urllib3/connectionpool.py", line 285, in _get_conn`
`    return conn or self._new_conn()`
`  File "/usr/lib/python3.8/site-packages/oci/_vendor/urllib3/connectionpool.py", line 994, in _new_conn`
`    conn = self.ConnectionCls(`
`  File "/usr/lib/python3.8/site-packages/oci/base_client.py", line 160, in __init__`
`    super(OCIConnection, self).__init__(*args, **kwargs)`
`TypeError: object.__init__() takes exactly one argument (the instance to initialize)`
``

When Tried with version 3.6, it runs absolutely smooth. 

Awaiting a response on this.

**Comment by bhagwatvyas** [comment]
@Kirandeep-Singh are you still facing this issue?

**Comment by zelrew-harvard** [comment]
I have the same problem with Python 3.10.10. 

```
config = from_file(profile_name="...")
secretclient = oci.secrets.SecretsClient(config)
secretcontents = secretclient.get_secret_bundle(key_ocid)
```

results in 

```
Traceback (most recent call last):
  File "/Users/name/Desktop/test.py", line 135, in <module>
    response = test()
  File "/Users/name/Desktop/test.py", line 25, in test
    secretcontents = secretclient.get_secret_bundle(keyOCID)
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/secrets/secrets_client.py", line 223, in get_secret_bundle
    return retry_strategy.make_retrying_call(
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/retry/retry.py", line 308, in make_retrying_call
    response = func_ref(*func_args, **func_kwargs)
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/base_client.py", line 535, in call_api
    response = self.request(request, allow_control_chars, operation_name, api_reference_link)
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/circuitbreaker.py", line 159, in wrapper
    return call(function, *args, **kwargs)
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/circuitbreaker.py", line 170, in call
    return func(*args, **kwargs)
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/base_client.py", line 677, in request
    response = self.session.request(
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/_vendor/requests/sessions.py", line 536, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/_vendor/requests/sessions.py", line 652, in send
    r = adapter.send(request, **kwargs)
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/_vendor/requests/adapters.py", line 447, in send
    resp = conn.urlopen(
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/_vendor/urllib3/connectionpool.py", line 697, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/_vendor/urllib3/connectionpool.py", line 286, in _get_conn
    return conn or self._new_conn()
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/_vendor/urllib3/connectionpool.py", line 1024, in _new_conn
    conn = self.ConnectionCls(
  File "/Users/name/.pyenv/versions/3.10.0/lib/python3.10/site-packages/oci/base_client.py", line 165, in __init__
    super(OCIConnection, self).__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```
