### ISSUE TITLE
Cannot upload anything through UploadManager class

### ISSUE THREAD

**Issue by mazzespazze** [oracle/oci-python-sdk#461]
I am trying to upload a stream directly into an Oracle Bucket through UploadManager. 

Here is the code snippet:
```python
from environs import Env
import oci

env = Env()
env.read_env()  # Read .env into os.environ
config = {'log_requests': False, 'additional_user_agent': '', 'pass_phrase': None,
          'user': env("USER_OCID"),
          'fingerprint': env("FINGERPRINT"), 
          'key_file': PATH_TO_KEY',
          'tenancy': env("TENANCY"),
          'region': env("REGION")}

um = oci.object_storage.UploadManager(config)

um.upload_stream(namespace_name=MY_NAMESPACE, 
                               bucket_name=MY_BUCKETNAME,
                               stream_ref="", 
                               object_name=MY_OBJECT_NAME)
```

Whatever is the value associated to `stream_ref` I always end up in the same error:

`Traceback (most recent call last):
  File "uploader.py", line 16, in <module>
    um.upload_stream(namespace_name=MY_NAMESPACE, bucket_name=MY_BUCKET_NAME,
  File "/lib/python3.9/site-packages/oci/object_storage/transfer/upload_manager.py", line 137, in upload_stream
    ma.new_upload()
  File "/lib/python3.9/site-packages/oci/object_storage/transfer/internal/multipart_object_assembler.py", line 403, in new_upload
    response = self.object_storage_client.create_multipart_upload(self.manifest["namespace"],
AttributeError: 'dict' object has no attribute 'create_multipart_upload'`

I am using python3.9 and oci version 2.55.1

**Comment by KartikShrikantHegde** [comment]
Hi @mazzespazze Thank you for reporting this issue. This seems like an issue with our Object Storage service and I will notify the Object Storage team to take a look.

**Comment by github-anurag** [comment]
@mazzespazze 
Please follow the example: https://github.com/oracle/oci-python-sdk/blob/master/examples/multipart_object_upload.py 

For uploading Stream you can use [upload_stream](https://github.com/oracle/oci-python-sdk/blob/299b738310333b36ccfcfa8960246b2d80f7136e/src/oci/object_storage/transfer/upload_manager.py#L52) method instead.

Please feel free to reopen the issue if you still see any issue.
