### ISSUE TITLE
problems running in CLI OCI

### ISSUE THREAD

**Issue by walzatem06** [oracle/oci-python-sdk#640]
hello, I am trying to run this and I get the following errors, everything I run from OCI cloud shell

 python3 showoci.py -i
Traceback (most recent call last):
  File "showoci.py", line 566, in <module>
    execute_extract()
  File "showoci.py", line 179, in execute_extract
    data = ShowOCIData(flags)
  File "/home/walzatem/oci-python-sdk/examples/showoci/oci-python-sdk/examples/showoci/showoci_data.py", line 46, in __init__
    self.service = ShowOCIService(flags)
  File "/home/walzatem/oci-python-sdk/examples/showoci/oci-python-sdk/examples/showoci/showoci_service.py", line 559, in __init__
    self.generate_signer_from_config(flags.config_file, flags.config_section)
  File "/home/walzatem/oci-python-sdk/examples/showoci/oci-python-sdk/examples/showoci/showoci_service.py", line 571, in generate_signer_from_config
    user=self.config["user"],
KeyError: 'user'

**Comment by adizohar** [comment]
You should check the instructions at this page - https://github.com/oracle/oci-python-sdk/tree/master/examples/showoci#3-executing-showoci-using-different-options

To run from cloud shell, you need to use
python3 showoci.py ii -dt

**Comment by walzatem06** [comment]
thank you it worked without problems

**Comment by adizohar** [comment]
Thank you, can you please close the ticket if all good
