### ISSUE TITLE
call mysql_client_composite_ops.copy_backup_and_wait_for_state display AttributeError: 'DbBackupsClient' object has no attribute 'get_work_request'

### ISSUE THREAD

**Issue by jansonkwo** [oracle/oci-python-sdk#664]
call  DbBackupsClientCompositeOperations copy_backup_and_wait_for_state, return：
Traceback (most recent call last):
  File "E:\Python\Python38\lib\site-packages\oci\mysql\db_backups_client_composite_operations.py", line 99, in copy_backup_and_wait_for_state
    self.client.get_work_request(wait_for_resource_id),
AttributeError: 'DbBackupsClient' object has no attribute 'get_work_request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MDS-Cross-Region-BackupCopy.py", line 36, in <module>
    copy_backup_response = mysql_client_composite_ops.copy_backup_and_wait_for_state(
  File "E:\Python\Python38\lib\site-packages\oci\mysql\db_backups_client_composite_operations.py", line 107, in copy_backup_and_wait_for_state
    raise oci.exceptions.CompositeOperationError(partial_results=[operation_result], cause=e)
oci.exceptions.CompositeOperationError

the copy backup request is submitted, creating, and SUCCEEDED.

**Comment by richachugh11** [comment]
Hi @jansonkwo , what version of the OCI Python SDK are you currently using? Have you tried updating it to the latest version?
