### ISSUE TITLE
oci.exceptions.RequestException When run python retrieve_audit_events.py

### ISSUE THREAD

**Issue by vipmike007** [oracle/oci-python-sdk#82]
testing env:
$ uname -a
Linux miketest 4.8.14-300.fc25.x86_64 #1 SMP Mon Dec 12 16:31:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[mcao@miketest examples]$ python --version
Python 2.7.12
[mcao@miketest examples]$ pip list |grep oci
oci                              2.0.6 

$ python retrieve_audit_events.py 
Traceback (most recent call last):
  File "retrieve_audit_events.py", line 95, in <module>
    end_time)
  File "retrieve_audit_events.py", line 54, in get_audit_events
    end_time=end_time).data
  File "/usr/lib/python2.7/site-packages/oci/pagination/pagination_utils.py", line 203, in list_call_get_all_results
    for response in list_call_get_all_results_generator(list_func_ref, 'response', *list_func_args, **list_func_kwargs):
  File "/usr/lib/python2.7/site-packages/oci/pagination/pagination_utils.py", line 271, in list_call_get_all_results_generator
    call_result = retry.DEFAULT_RETRY_STRATEGY.make_retrying_call(list_func_ref, *list_func_args, **list_func_kwargs)
  File "/usr/lib/python2.7/site-packages/oci/retry/retry.py", line 271, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "/usr/lib/python2.7/site-packages/oci/audit/audit_client.py", line 229, in list_events
    response_type="list[AuditEvent]")
  File "/usr/lib/python2.7/site-packages/oci/base_client.py", line 221, in call_api
    response = self.request(request)
  File "/usr/lib/python2.7/site-packages/oci/base_client.py", line 332, in request
    raise exceptions.RequestException(e)
oci.exceptions.RequestException: HTTPSConnectionPool(host='audit.us-asburn-1.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/auditEvents?compartmentId=ocid1.tenancy.oc1..aaaaaaaaqrol7kkrruav76ou65we6n4yj646gdt554ssiecdpqorr4jnyz7a&endTime=2018-11-01T09%3A00%3A46.383604Z&startTime=2018-10-27T09%3A00%3A46.383604Z (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7c162abb10>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Is audit.us-asburn-1.oraclecloud.com the right host to get the audit data? why my laptop can not parse the address?

**Comment by arthall** [comment]
The endpoint for us-ashburn-1 is audit.us-ashburn-1.oraclecloud.com.  I suspect the `region` value in your config is missing the `h` in ashburn.  Please check your config file to see if that is the issue.

**Comment by vipmike007** [comment]
oops. Sorry for that , it looks good now.
